server:
  port: 8081
  servlet:
    context-path: /
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer